
# Stage 1: Build the Next.js app
FROM node:18-bullseye-slim AS builder
WORKDIR /app

RUN apt-get update && apt-get install -y python3 build-essential && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json* ./
RUN npm install

COPY . .


RUN npm run build

# Stage 2: Run the production server
FROM node:18-bullseye-slim
WORKDIR /app


COPY --from=builder /app ./

EXPOSE 3000

CMD ["npm", "run", "start"]
